### ISSUE TITLE
Upgrade to latest spec v2.4.0

### ISSUE THREAD

**Issue by pagrawal10** [swaggest/go-asyncapi#15]
Are there any plans to upgrade the spec to the latest AsyncAPI version (v2.4.0)?

**Comment by vearutop** [comment]
Hi, I've started some work in https://github.com/swaggest/go-asyncapi/tree/spec-2.4.0, but haven't finished it yet. Hopefully, will have some capacity to work on it again soon.

**Comment by pagrawal10** [comment]
Is there any timeline by which we should expect it to be released?

**Comment by vearutop** [comment]
Please try [`v0.7.1`](https://github.com/swaggest/go-asyncapi/releases/tag/v0.7.1) and file issues if you face any.
