### ISSUE TITLE
Update Kafka binding Version

### ISSUE THREAD

**Issue by pagrawal10** [swaggest/go-asyncapi#17]
Please update the kafka binding version in [entities.go](https://github.com/swaggest/go-asyncapi/blob/394e1623acadf7784fb497e15608898c1aa5f5e2/spec-2.4.0/entities.go#L5156) as the current version is v0.2.0
as per [AsyncAPI Kafka Bindings](https://github.com/asyncapi/bindings/tree/master/kafka#version)

**Comment by vearutop** [comment]
Operation schema is still marked as 0.1.0 in that repo https://github.com/asyncapi/bindings/blob/master/kafka/json_schemas/operation.json#L25.
