### ISSUE TITLE
Example documentation for v2.4.0

### ISSUE THREAD

**Issue by steinzi** [swaggest/go-asyncapi#19]
Would it be possible to get the readme example to show the v2.4.0 spec as well?
![Alt Text](https://media4.giphy.com/media/SA00ENEG45W8yNao7V/giphy.gif)

**Comment by vearutop** [comment]
Will add, and in meanwhile please check https://github.com/swaggest/go-asyncapi/blob/master/reflector/asyncapi-2.4.0/example_test.go if you haven't.
